import os

import unittest
import json
import math
from unittest.mock import patch
from flask.testing import FlaskClient
from iiify.app import app

def mockJsonResponse(payload):
    class MockResponse:
        status_code = 200
        def json(self):
            return payload

        def raise_for_status(self):
            return

    return MockResponse()

def mockResponse(fixture):
    with open(fixture, "r") as file:
        return mockJsonResponse(json.load(file))

class TestVideo(unittest.TestCase):

    def setUp(self) -> None:
        app.config['CACHE_TYPE'] = "NullCache"
        self.test_app = FlaskClient(app)

    def test_v3_single_video_manifest(self):
        resp = self.test_app.get("/iiif/3/youtube-7w8F2Xi3vFw/manifest.json")
        self.assertEqual(resp.status_code, 200)
        manifest = resp.json

        self.assertEqual(len(manifest['items']),1,f"Expected 1 canvas but got: {len(manifest['items'])}")   

    def test_v3_h264_MPEG4_OGG_Theora(self):
        resp = self.test_app.get("/iiif/3/taboca_201002_03/manifest.json")
        self.assertEqual(resp.status_code, 200)
        manifest = resp.json
        self.assertEqual(len(manifest['items']),251,f"Expected 251 canvases but got: {len(manifest['items'])}")
        self.assertEqual("h.264 MPEG4".lower() in resp.text.lower(), True, f"Expected the string 'h.264 MPEG4'")
        self.assertEqual("OGG Theora".lower() in resp.text.lower(), True, f"Expected the string 'OGG Theora'")

    def test_vtt_autogenerated(self):
        resp = self.test_app.get("/iiif/3/youtube-SvH4fbjOT0A/manifest.json?recache=true")
        self.assertEqual(resp.status_code, 200)
        manifest = resp.json

        self.assertEqual(len(manifest['items']),1,f"Expected 1 canvas but got: {len(manifest['items'])}")
        self.assertTrue('annotations' in manifest['items'][0], "Expected annotations in manifest")
        self.assertTrue(isinstance(manifest['items'][0]['annotations'], list), "Expected annotations to be a list")
        self.assertEqual(len(manifest['items'][0]['annotations']), 1, "Expected 1 item in annotations")
        annotationPage = manifest['items'][0]['annotations'][0]
        self.assertEqual(annotationPage['type'], 'AnnotationPage', "Expected annotations to contain annotation page")

        self.assertTrue('items' in annotationPage and isinstance(annotationPage['items'],list) and len(annotationPage['items']) == 1, f"Expected annotation page to contain a list of items which contains 1 item. Found {annotationPage['items']}")
        annotation = annotationPage['items'][0]
        self.assertEqual(annotation['type'], 'Annotation', "Expected annotationPage to contain annotations")
        self.assertEqual(annotation['motivation'], 'supplementing', "Expected annotation to have the supplementing annotation")
        self.assertTrue('body' in annotation, "Expected annotation to have a body")
        body = annotation['body']
        self.assertEqual(body['type'],'Text', "Expected body to have a type text")
        self.assertEqual(body['format'],'text/vtt', "Expected body to have a type text")
        self.assertEqual(body['label']['en'][0], "autogenerated", "Expected VTT file to have the label autogenerated")
        self.assertFalse("language" in body, "We don't know the language for this item so there shouldn't be a language specified")
        self.assertEqual(body['id'], "https://localhost/iiif/resource/youtube-SvH4fbjOT0A/34C3_-_International_Image_Interoperability_Framework_IIIF_Kulturinstitutionen_schaffen_interop-SvH4fbjOT0A.autogenerated.vtt","Unexpected URL for the VTT file")

    def test_vtt_multilingual(self):
        resp = self.test_app.get("/iiif/3/cruz-test/manifest.json?recache=true")
        self.assertEqual(resp.status_code, 200)
        manifest = resp.json

        canvas = manifest['items'][0]
        self.assertTrue('annotations' in canvas, 'Expected annotations in Canvas')
        self.assertEqual(len(canvas['annotations']), 1, 'Expected one AnnotationPage')
        annotations = canvas['annotations'][0]['items']
        self.assertEqual(len(annotations), 104, 'Expected all 104 langues')

        # Check welsh
        for item in annotations:
            self.assertTrue('language' in item['body'], f"All vtt files should have a language: {item}")
            if item['body']['language'] == 'cy':
                self.assertEqual(item['body']['id'], 'https://localhost/iiif/resource/cruz-test/cruz-test.cy.vtt', 'Unexpected link for the Welsh vtt file')

    def test_newsitem(self):
        resp = self.test_app.get("/iiif/3/CSPAN3_20180217_164800_Poplar_Forest_Archaeology/manifest.json?recache=true")
        self.assertEqual(resp.status_code, 200)
        manifest = resp.json

        canvas = manifest['items'][0]
        annoPages = canvas['items'][0]
        annotations = annoPages['items']
        self.assertEqual(len(annotations), math.floor(780.89 / 60), 'Expected the video to contain the 13min video split into 1 minute segments')

        # Check vtt file
        self.assertTrue('annotations' in canvas, "Expected canvas to have annotations")
        vttFile = canvas['annotations'][0]['items'][0]['body']['id']
        self.assertTrue(vttFile.endswith("/iiif/vtt/streaming/CSPAN3_20180217_164800_Poplar_Forest_Archaeology.vtt"),f"Expected vttFile to be located at /iiif/vtt/streaming/CSPAN3_20180217_164800_Poplar_Forest_Archaeology.vtt but found it at {vttFile}")

        resp = self.test_app.get("/iiif/vtt/streaming/CSPAN3_20180217_164800_Poplar_Forest_Archaeology.vtt")
        checkLine=False
        for line in resp.text.split("\n"):
            if checkLine:
                self.assertEqual("00:01:02.000 --> 00:01:03.000", line, "Expected the timecode to be over a minute as its the second video")
                break    
            if line.startswith("28"):
                checkLine=True
        # 28
        # 00:01:02.000 -> 00:01:02.000
        # I AM THE DIRECTOR OF ARCHAEOLOGY

        # Test thumbnail nav
        self.assertTrue("structures" in manifest, "Expected manifest to have a structure")

        range = manifest["structures"][0]
        self.assertTrue("behavior" in range, "Range should have a behavior property")
        self.assertTrue(isinstance(range["behavior"], list), "Behavior should be a list")
        self.assertEqual("thumbnail-nav", range["behavior"][0], "Range should have the thumbnail-nav behavior")

        self.assertEqual(26, len(range["items"]), "Expected 26 thumbnails")

        second_thumb = range["items"][1]
        self.assertEqual("https://iiif.archive.org/iiif/CSPAN3_20180217_164800_Poplar_Forest_Archaeology/CSPAN3_20180217_164800_Poplar_Forest_Archaeology/canvas#t=1,57", second_thumb["items"][0]["id"], "Link to canvas not correct in thumbnail range")

        self.assertEqual("https://archive.org/download/CSPAN3_20180217_164800_Poplar_Forest_Archaeology/CSPAN3_20180217_164800_Poplar_Forest_Archaeology.thumbs/CSPAN3_20180217_164800_Poplar_Forest_Archaeology_000057.jpg", second_thumb["thumbnail"][0]["id"], "Thumbnail-nav link not correct.")

    def test_media_types(self):
        resp = self.test_app.get("/iiif/3/coitx-Inside_the_Movies_-_Shang-Chi_and_the_Legend_of_the_Ten_Rings/manifest.json?recache=true")
        self.assertEqual(resp.status_code, 200)
        manifest = resp.json

        body = manifest["items"][0]["items"][0]["items"][0]["body"]["items"]

        for item in body:
            name = item['id']
            format = item['format']
            if name.endswith("mov"):
                self.assertEqual("video/quicktime", format, "Unexpected mimetype for Analyzing Ten_Rings.HD.mov")
            elif name.endswith("mp4"):
                self.assertEqual("video/mp4", format, "Unexpected mime type for Legend_of_the_Ten_Rings.mp4")

    def test_multitype_video(self):
        # Video with images as well as an mp4. 
        # Should have both video and image canvases 
        resp = self.test_app.get("/iiif/3/2025-highland-house-walkthrough-ma/manifest.json?recache=true")
        self.assertEqual(resp.status_code, 200)
        manifest = resp.json
        
        self.assertEqual(28, len(manifest["items"]), "Expected 28 canvases")

    @patch("requests.get")
    def test_v3_video_original_without_derivatives(self, metadataPatch):
        """https://github.com/internetarchive/iiif/issues/171

        DontBeaS1947 is a 1947 film uploaded with three separate originals whose format
        is in VIDEO_FORMATS, but only DontBeaS1947.mpeg has derivatives of its own:

            DontBeaS1947.avi       Cinepack      no derivatives, video/x-msvideo
            DontBeaS1947.mpeg      MPEG2         derivatives: h.264, 512Kb MPEG4, Ogg Video
            DontBeaS1947_edit.mp4  HiRes MPEG4   no derivatives, video/mp4

        The .avi sorts first, so the first iteration used to fall through an `else: pass`
        and leave `body` unbound, 500ing the whole manifest. Had it sorted last, `body`
        would instead have still held the .mpeg canvas's Choice and painted this canvas
        with another original's derivatives - which is what the disjointness assertion
        at the end of this test guards against.

        Deliberately fixture-backed rather than live: this item's derivative set is
        precisely what is under test, so a future re-derive on the item must not be able
        to turn this test green for the wrong reason.
        """
        def mock_get(url, *args, **kwargs):
            if "/metadata/" in url:
                return mockResponse("tests/fixtures/metadata/DontBeaS1947.json")
            if url.endswith("info.json"):
                # Cantaloupe, called for the item's thumbnails - not under test here.
                return mockJsonResponse({
                    "@context": "http://iiif.io/api/image/2/context.json",
                    "@id": url[:-len("/info.json")],
                    "protocol": "http://iiif.io/api/image",
                    "profile": ["http://iiif.io/api/image/2/level2.json"],
                    "width": 320,
                    "height": 240,
                })
            raise AssertionError(f"Unexpected request while building the manifest: {url}")

        metadataPatch.side_effect = mock_get

        # recache=true is required: setUp's NullCache never takes effect (flask_caching is
        # already initialised against the FileSystemCache in ./cache by import time), so
        # without it this asserts against whatever a previous run left on disk.
        resp = self.test_app.get("/iiif/3/DontBeaS1947/manifest.json?recache=true")
        self.assertEqual(resp.status_code, 200)
        manifest = resp.json

        canvases = {canvas['id']: canvas for canvas in manifest['items']}
        prefix = "https://iiif.archive.org/iiif/DontBeaS1947"
        self.assertEqual(
            set(canvases),
            {f"{prefix}/DontBeaS1947/canvas", f"{prefix}/DontBeaS1947_edit/canvas"},
            "Expected a canvas for the .mpeg and for the playable _edit.mp4, and none "
            "for the underived, unplayable .avi")

        def bodyItems(canvas):
            body = canvas['items'][0]['items'][0]['body']
            return body['items'] if body['type'] == 'Choice' else [body]

        # The .mpeg original has derivatives, so its canvas is a Choice over them plus
        # the original itself.
        mpeg = bodyItems(canvases[f"{prefix}/DontBeaS1947/canvas"])
        self.assertEqual(
            [item['id'] for item in mpeg],
            [f"https://archive.org/download/DontBeaS1947/DontBeaS1947{suffix}"
             for suffix in ("_512kb.mp4", ".mpeg", ".mp4", ".ogv")],
            "Expected the .mpeg canvas to offer its derivatives in VIDEO_FORMATS order")

        # The _edit.mp4 original has no derivatives but is itself playable, so its canvas
        # gets a single body built from the original, as the audio branch does.
        edit = bodyItems(canvases[f"{prefix}/DontBeaS1947_edit/canvas"])
        self.assertEqual(len(edit), 1, "Expected a single body for the _edit.mp4 canvas")
        self.assertEqual(
            edit[0]['id'],
            "https://archive.org/download/DontBeaS1947/DontBeaS1947_edit.mp4")
        self.assertEqual(edit[0]['type'], 'Video')
        self.assertEqual(edit[0]['format'], 'video/mp4')

        # The regression guard: no canvas may be painted with another original's bodies.
        self.assertEqual(
            {item['id'] for item in mpeg} & {item['id'] for item in edit},
            set(),
            "A canvas is showing another original's derivatives")

        self.assertNotIn(
            "DontBeaS1947.avi", resp.text,
            "The underived, unplayable .avi should not appear in the manifest at all")

    @patch("requests.get")
    def test_v3_video_with_no_renderable_original(self, metadataPatch):
        """An item where every video original is underived and unplayable.

        Pins the edge case that skipping creates: such an item used to 500 and now
        returns a manifest with no canvases rather than one canvas per dead player.
        Documented deliberately - see https://github.com/internetarchive/iiif/issues/171.
        """
        with open("tests/fixtures/metadata/DontBeaS1947.json", "r") as file:
            metadata = json.load(file)

        # Strip the item back to its one underived, unplayable original (the Cinepack .avi).
        metadata['files'] = [
            f for f in metadata['files']
            if f.get('source') != 'derivative'
            and f['name'] not in ('DontBeaS1947.mpeg', 'DontBeaS1947_edit.mp4')]

        def mock_get(url, *args, **kwargs):
            if "/metadata/" in url:
                return mockJsonResponse(metadata)
            if url.endswith("info.json"):
                return mockJsonResponse({
                    "@context": "http://iiif.io/api/image/2/context.json",
                    "@id": url[:-len("/info.json")],
                    "protocol": "http://iiif.io/api/image",
                    "profile": ["http://iiif.io/api/image/2/level2.json"],
                    "width": 320,
                    "height": 240,
                })
            raise AssertionError(f"Unexpected request while building the manifest: {url}")

        metadataPatch.side_effect = mock_get

        resp = self.test_app.get("/iiif/3/DontBeaS1947/manifest.json?recache=true")
        self.assertEqual(resp.status_code, 200, "Expected a manifest rather than a 500")
        self.assertEqual(resp.json['items'], [], "Expected no canvases")
        self.assertNotIn('behavior', resp.json, "auto-advance makes no sense with no canvases")


if __name__ == '__main__':
    unittest.main()