on: push
jobs:
  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
    with:
      BASE_DOMAIN: 'ux-fnf-misc.archive.org'
      NOMAD_VAR_CHECK_PATH: '/iiif/documentation'
      NOMAD_VAR_CHECK_PROTOCOL: 'http'
      NOMAD_ADDR: 'https://ux-fnf-misc.archive.org/'
      NOMAD_VAR_COUNT_CANARIES: 0
      # NOMAD_VAR_CHECK_TIMEOUT: '10m'
      NOMAD_VAR_HOSTNAMES: '["iiif.ux-fnf-misc.archive.org"]'
      NOMAD_VAR_PORTS: '{8080 = "http", 8182 = "cantaloupe"}'
      NOMAD_VAR_FORCE_PULL: 'true'

  deploy:
    environment:
      name: development
      url: https://internetarchive-iiif-${{ env.BRANCH_NAME }}.ux-fnf-misc.archive.org
    runs-on: ubuntu-latest
    needs: cicd
    steps:
      - name: Checkout # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - name: Export BRANCH_NAME # store branch name in $BRANCH_NAME
        run: echo BRANCH_NAME=`git rev-parse --abbrev-ref HEAD` >> $GITHUB_ENV
